name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello World ! La CI fonctionne"

      - name: Afficher la date
        run: date
        